name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
            xcodebuild clean archive \
            -project ${{ env.projname }}.xcodeproj \
            -scheme ${{ env.projname }} \
            -archivePath ${{ env.projname }} \
            -allowProvisioningUpdates
                xcodebuild clean archive \
            -project ${{ env.projname }}.xcodeproj \
            -scheme ${{ env.projname }} \
            -archivePath ${{ env.projname }} \
            -allowProvisioningUpdates
      - name: Upload built app
        uses: actions/upload-artifact@master
        with:
          name: app-${{ needs.preparation.outputs.version }}
          path: |
            Release/${{ env.projname }}.dmg
            Release/${{ env.projname }}.app
          
